# Generated by Django. Add long_description to SouffleApp
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souffleapp',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
