# Generated by Django 5.2.4 on 2025-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0002_souffleapp_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souffleapp',
            name='url',
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Ingredientes necesarios'),
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Lo que el cliente aprenderá'),
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='materials',
            field=models.TextField(blank=True, help_text='Materiales que usará el cliente'),
        ),
        migrations.AddField(
            model_name='souffleapp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del curso', max_digits=8),
        ),
    ]
