# Generated by Django 5.2.4 on 2025-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0003_remove_souffleapp_url_souffleapp_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souffleapp',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='souffleapp',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='souffleapp',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='souffleapp',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='souffleapp',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
