# Generated by Django 5.2.4 on 2025-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0004_alter_souffleapp_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souffleapp',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
