# Generated by Django 5.2.4 on 2025-10-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0005_alter_souffleapp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souffleapp',
            name='price',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
