# Generated by Django 5.2.4 on 2025-10-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas_totales', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souffleApp.souffleapp')),
            ],
            options={
                'verbose_name': 'Venta Simulada',
                'verbose_name_plural': 'Ventas Simuladas',
            },
        ),
    ]
