# Generated by Django 5.2.4 on 2025-10-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0008_ventasimulada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['fecha', 'hora']},
        ),
    ]
