# Generated by Django 5.2.4 on 2025-10-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souffleApp', '0009_alter_horario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='compra',
            name='email_usuario',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_curso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='hora_curso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_curso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio_pagado',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='compra',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='souffleApp.souffleapp'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='souffleApp.horario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VentaSimulada',
        ),
    ]
