# Generated by Django 5.2.4 on 2025-11-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souffleApp", "0011_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="author",
            new_name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(max_length=2000),
        ),
    ]
